PET MICROPLASTICS TEST

In [61]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier, export_graphviz                 
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
import graphviz
import matplotlib.pylab as plt

petdata = pd.read_excel ('pet.xlsx')
X = petdata.drop(columns=['PrPET-RE'])
y= petdata['PrPET-RE'].astype(str)
model = DecisionTreeClassifier().fit(X, y)
pipe = Pipeline ([("scale", StandardScaler()),
                  ("model",DecisionTreeClassifier(random_state=0))])

pipe.fit(X, y)
pred = pipe.predict(X)

# Export the decision tree as a .dot file
pettree = export_graphviz(model, out_file='petmp.dot', 
                feature_names=['CIPConc','Temperature','pH','Ionic strength' ],
                class_names=sorted(y.unique()), label='all', 
                filled=True, rounded=True)

In [58]:
!pip install graphviz

Collecting graphviz
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     -------------------------------------- 47.0/47.0 kB 334.5 kB/s eta 0:00:00
Installing collected packages: graphviz
Successfully installed graphviz-0.20.1

In [66]:
pd.DataFrame(pred)

        0
0    64.1
1   72.8
2   72.8
3    52.9
4   72.8
5    87.3
6      71
7    79.3
8   75.8
9    89.7
10   65.7
11  72.8
12   89.3
13     71
14  77.8
15  77.8
16     85
17  72.8
18  72.8
19  72.8
20  72.0
21     81
22  70.8
23   74.1
24  82.8
25     68
26   53.3
27   85.7
28   80.1
29   75.7